//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clientews.manejoidentidad01 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soi.avvillas.com/ManejoIdentidad/WSBA_ManejoIdentidad_autenticar", ConfigurationName="manejoidentidad01.WSBA_ManejoIdentidad_autenticar_FM", ProtectionLevel =System.Net.Security.ProtectionLevel.Sign)]
    public interface WSBA_ManejoIdentidad_autenticar_FM {
        
        // CODEGEN: Generating message contract since the operation autenticar is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        clientews.manejoidentidad01.autenticarResponse1 autenticar(clientews.manejoidentidad01.autenticarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<clientews.manejoidentidad01.autenticarResponse1> autenticarAsync(clientews.manejoidentidad01.autenticarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soi.avvillas.com/ManejoIdentidad/WSBA_ManejoIdentidad_autenticar")]
    public partial class autenticar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private oe_Autenticacion oe_entradaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public oe_Autenticacion oe_entrada {
            get {
                return this.oe_entradaField;
            }
            set {
                this.oe_entradaField = value;
                this.RaisePropertyChanged("oe_entrada");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soi.avvillas.com/ManejoIdentidad/WSBA_ManejoIdentidad_autenticar")]
    public partial class oe_Autenticacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strUsuarioField;
        
        private string strContrasenaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string strUsuario {
            get {
                return this.strUsuarioField;
            }
            set {
                this.strUsuarioField = value;
                this.RaisePropertyChanged("strUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string strContrasena {
            get {
                return this.strContrasenaField;
            }
            set {
                this.strContrasenaField = value;
                this.RaisePropertyChanged("strContrasena");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soi.avvillas.com/ManejoIdentidad/WSBA_ManejoIdentidad_autenticar")]
    public partial class os_AutenticacionResp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soi.avvillas.com/ManejoIdentidad/WSBA_ManejoIdentidad_autenticar")]
    public partial class autenticarResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private os_AutenticacionResp os_salidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public os_AutenticacionResp os_salida {
            get {
                return this.os_salidaField;
            }
            set {
                this.os_salidaField = value;
                this.RaisePropertyChanged("os_salida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autenticarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soi.avvillas.com/ManejoIdentidad/WSBA_ManejoIdentidad_autenticar", Order=0)]
        public clientews.manejoidentidad01.autenticar autenticar;
        
        public autenticarRequest() {
        }
        
        public autenticarRequest(clientews.manejoidentidad01.autenticar autenticar) {
            this.autenticar = autenticar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autenticarResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soi.avvillas.com/ManejoIdentidad/WSBA_ManejoIdentidad_autenticar", Order=0)]
        public clientews.manejoidentidad01.autenticarResponse autenticarResponse;
        
        public autenticarResponse1() {
        }
        
        public autenticarResponse1(clientews.manejoidentidad01.autenticarResponse autenticarResponse) {
            this.autenticarResponse = autenticarResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSBA_ManejoIdentidad_autenticar_FMChannel : clientews.manejoidentidad01.WSBA_ManejoIdentidad_autenticar_FM, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSBA_ManejoIdentidad_autenticar_FMClient : System.ServiceModel.ClientBase<clientews.manejoidentidad01.WSBA_ManejoIdentidad_autenticar_FM>, clientews.manejoidentidad01.WSBA_ManejoIdentidad_autenticar_FM {
        
        public WSBA_ManejoIdentidad_autenticar_FMClient() {
        }
        
        public WSBA_ManejoIdentidad_autenticar_FMClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSBA_ManejoIdentidad_autenticar_FMClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSBA_ManejoIdentidad_autenticar_FMClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSBA_ManejoIdentidad_autenticar_FMClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clientews.manejoidentidad01.autenticarResponse1 clientews.manejoidentidad01.WSBA_ManejoIdentidad_autenticar_FM.autenticar(clientews.manejoidentidad01.autenticarRequest request) {
            return base.Channel.autenticar(request);
        }
        
        public clientews.manejoidentidad01.autenticarResponse autenticar(clientews.manejoidentidad01.autenticar autenticar1) {
            clientews.manejoidentidad01.autenticarRequest inValue = new clientews.manejoidentidad01.autenticarRequest();
            inValue.autenticar = autenticar1;
            clientews.manejoidentidad01.autenticarResponse1 retVal = ((clientews.manejoidentidad01.WSBA_ManejoIdentidad_autenticar_FM)(this)).autenticar(inValue);
            return retVal.autenticarResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clientews.manejoidentidad01.autenticarResponse1> clientews.manejoidentidad01.WSBA_ManejoIdentidad_autenticar_FM.autenticarAsync(clientews.manejoidentidad01.autenticarRequest request) {
            return base.Channel.autenticarAsync(request);
        }
        
        public System.Threading.Tasks.Task<clientews.manejoidentidad01.autenticarResponse1> autenticarAsync(clientews.manejoidentidad01.autenticar autenticar) {
            clientews.manejoidentidad01.autenticarRequest inValue = new clientews.manejoidentidad01.autenticarRequest();
            inValue.autenticar = autenticar;
            return ((clientews.manejoidentidad01.WSBA_ManejoIdentidad_autenticar_FM)(this)).autenticarAsync(inValue);
        }
    }
}
